### ISSUE TITLE
Milestone 3 tasklist

### ISSUE THREAD

**Issue by feliciagan** [feliciagan/orbital-sepper#21]
- [x] arrange meetup feature
- [x] edit profile feature
- [x] like post feature
- [x] anon post feature
- [x] search feature
- [x] email verification
- [x] change password
- [x] reset password
- [x] delete account
